[general]
live_config_reload = true

#[terminal.shell]
#program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
option_as_alt = "Both"
resize_increments = true
startup_mode = "Windowed"
title = "Alacritty"

[window.identity]
class = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0

[font]
size = 11
builtin_box_drawing = true

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.italic]
family = "CodeNewRoman Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CodeNewRoman Nerd Font"
style = "Bold Italic"

[scrolling]
history = 0
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ""

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[colors.normal]
black = "#000000"
red = "#cc0403"
green = "#19cb00"
yellow = "#cecb00"
blue = "#0d73cc"
magenta = "#cb1ed1"
cyan = "#0dcdcd"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#f2201f"
green = "#23fd00"
yellow = "#fffd00"
blue = "#1a8fff"
magenta = "#fd28ff"
cyan = "#14ffff"
white = "#ffffff"
